name: Deploy infra (Terraform Apply)

on:
 push:
    branches:
      - main

jobs:
 terraform-apply:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '>=1.7.5'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Terraform Init
      run: terraform init
    
    - name: Set Terraform log level and workspace
      run: |
        export TF_LOG=DEBUG
        terraform workspace select default || terraform workspace new default

    - name: Terraform Apply
      run: terraform apply --auto-approve
      timeout-minutes: 5
